### ISSUE TITLE
upgrade arrow version for hook and line

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/pyFieldSoftware#149]
Right now it crashes with the more updated version 14,15 that we use for the other software. @jimfellows-NOAA has already done a lot of the legwork on how to make the update happen.

**Comment by jimfellows-NOAA** [comment]
Seems like both replace and shift should be available:
* https://arrow.readthedocs.io/en/latest/#replace-shift
* https://arrow.readthedocs.io/en/latest/#arrow.arrow.Arrow.shift
* https://arrow.readthedocs.io/en/latest/#arrow.arrow.Arrow.replace

But the way replace is being used on line 77 of Sites.py:
```python
        elif filter == "all":
            params = [arrow.now('US/Pacific').replace(years=-100).format('YYYY-MM-DDTHH:mm:ss'),]
            print(params)
```
could be better if replaced with:
```python
        elif filter == "all":
            params = [arrow.now('US/Pacific').shift(years=-100).format('YYYY-MM-DDTHH:mm:ss'),]
            print(params)
```
I think the goal is getting all sites, so going back 100 years does the trick, and shift should work there.  15.4 doesn't seem to allow the first example with replace.


```
ERROR:FramUtil.py:118:[Qt]Traceback (most recent call last):
  File "C:\Users\james.fellows\dev\GitHub\pyFieldSoftware\py\hookandline_hookmatrix\Sites.py", line 77, in retrieveSites
    params = [arrow.now('US/Pacific').replace(years=-100).format('YYYY-MM-DDTHH:mm:ss'),]
  File "C:\Users\james.fellows\dev\GitHub\pyFieldSoftware\virtualenv\field_software\venv2\lib\site-packages\arrow\arrow.py", line 612, in replace
    raise AttributeError('unknown attribute: "{}"'.format(key))
AttributeError: unknown attribute: "years"
```

I think the only places I see using replace in a way that won't work with the newer version is in survey_backdeck\Sites.py and hookandline_hookmatrix\Sites.py.  Everything else looks like it should work, and seems pretty unlikely that upgrading to 0.15.4 for other software will significantly alter any behavior.
